# Numpy

In [1053]:
#numpy array
#lst-list
#lstArr-list array
import numpy as np
lst=[1,2,3,4,5,6]
lstArr = np.array(lst)
print(lstArr[0])

1


In [1054]:
import numpy as np
data=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [1055]:
#numpy array properties
print(data.ndim)
print(data.size)
print(data.shape)

2
9
(3, 3)


In [1034]:
#numpy array functions
#arange-fills list with values from range
x=np.arange(1,30,5)
print(x.shape)
print(x)


(6,)
[ 1  6 11 16 21 26]


In [1035]:
#reshape-rehapes matrix of list or flattens a matrix
x=x.reshape(2,3)
print(x.shape)
print(x)

x=x.reshape(6)
print(x.shape)
print(x)

(2, 3)
[[ 1  6 11]
 [16 21 26]]
(6,)
[ 1  6 11 16 21 26]


In [1036]:
#append-adds value to list but flattens it too
x=np.append(x,[30,3,2])
print(x)

[ 1  6 11 16 21 26 30  3  2]


In [1037]:
#delete
x=np.delete(x,0)
print(x)

[ 6 11 16 21 26 30  3  2]


In [1038]:
#sort
x=np.sort(x)
print(x)

[ 2  3  6 11 16 21 26 30]


In [1039]:
#indexing and slicing
print(x)
print(x[0])
#index 1 to 3
print(x[1:3])


[ 2  3  6 11 16 21 26 30]
2
[3 6]


In [1040]:
#beginning to index
print(x[:5])
print(x[:2])


[ 2  3  6 11 16]
[2 3]


In [1041]:
#index to end
print(x[2:])
print(x[5:])


[ 6 11 16 21 26 30]
[21 26 30]


In [1042]:
#negative values-  reverse
print(x)
print(x[-2:])#index 2 from opposite side
print(x[-5:])


[ 2  3  6 11 16 21 26 30]
[26 30]
[11 16 21 26 30]


In [1043]:
#using step
print(x)
print(x[1:5:1])
print(x[1:5:2])


[ 2  3  6 11 16 21 26 30]
[ 3  6 11 16]
[ 3 11]


In [1044]:
#negative step reverses number
print(x)
print(x[::-1])

[ 2  3  6 11 16 21 26 30]
[30 26 21 16 11  6  3  2]


In [1045]:
#conditions as index
print(x[x>4])
print(x[x%2==0])

[ 6 11 16 21 26 30]
[ 2  6 16 26 30]


In [1046]:
#combining conditions
print(x)
print(x[(x>4) & (x%2==0)])

[ 2  3  6 11 16 21 26 30]
[ 6 16 26 30]


In [1047]:
#array with 1-100 and 
# prints all divisible by 5 and 3
n=np.arange(1,101)
print(n[(n%3==0)&(n%5==0)])
#by 5 or 3
print(n[(n%3==0)|(n%5==0)])
#even numbers
print(n[(n%2==0)])
y=(n[(n%2==0)])
print(y.size)

[15 30 45 60 75 90]
[  3   5   6   9  10  12  15  18  20  21  24  25  27  30  33  35  36  39
  40  42  45  48  50  51  54  55  57  60  63  65  66  69  70  72  75  78
  80  81  84  85  87  90  93  95  96  99 100]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
50


In [1048]:
#array operations
print(n)
#sum of all numbers in list
print(n.sum())
#sum of portion
print(n[(n%2==0)].sum())
#maximum 
print(n[(n%2==0)].max())
#minimum
print(n[(n%2==0)].min())

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
5050
2550
100
2


In [1049]:
#performing operations
print(x)
print(x*2)
print(x**2)
print(x[:3])
print(x[:3].sum())

[ 2  3  6 11 16 21 26 30]
[ 4  6 12 22 32 42 52 60]
[  4   9  36 121 256 441 676 900]
[2 3 6]
11


Statistics

In [1050]:
#peforming statistical functions
a=np.array([14,18,19,24,26,33,42,55,67])
#mean
print(np.mean(a))
#median
print(np.median(a))
#variance
print(np.var(a))
#std
print(np.std(a))

#numbers greater than mean
print(a[a>=np.mean(a)])

#numbers greater than median
print(a[a>=np.median(a)])

33.111111111111114
26.0
292.5432098765432
17.10389458212787
[42 55 67]
[26 33 42 55 67]


Project

In [1052]:
import numpy as np

data = np.array([150000, 125000, 320000, 540000, 200000, 120000, 160000, 230000, 280000, 290000, 300000, 500000, 420000, 100000, 150000, 280000])
def deviate(lst):
    dev=np.std(lst)
    mn=np.mean(lst)
    dif1=mn-dev
    dif2=mn+dev
    num=0
    for i in lst:
        if i >= dif1 and i<=dif2:
            num+=1

    return num

devs=deviate(data)
print(devs/data.size*100)

62.5
